version: '3.6'

services:
  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.your.domain`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=tlschallenge"
    networks:
      - reverse-proxy
      - services

networks:
  reverse-proxy:
    external: true
  services:
    external: true
