version: '3.6'

services:
  traefik:
    image: traefik:v2.1
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
      - services
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:${TRAEFIK_ACME_STORAGE:-/etc/traefik/acme.json}
    command:
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-example@your.domain.com}
      - --certificatesresolvers.letsencrypt.acme.storage=${TRAEFIK_ACME_STORAGE:-/etc/traefik/acme.json}
      - --providers.docker.network=${REVERSE_PROXY_NETWORK:-reverse-proxy}
    logging:
      driver: ${LOG_DRIVER:-json-file}
      options:
        max-size: ${LOG_MAX_SIZE:-4m}
        max-file: ${LOG_MAX_FILE:-10}

networks:
  reverse-proxy:
    external:
      name: ${REVERSE_PROXY_NETWORK:-reverse-proxy}
  services:
    external:
      name: ${SERVICES_NETWORK:-services}
