log:
  level: DEBUG

entryPoints:
  traefik:
    address: ":80"
  traefik-secure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@your-domain.org
      httpChallenge:
        entryPoint: traefik

providers:
  docker:
    watch: true
    exposedByDefault: false
